<?php View::notify(); ?>

<div class="container-fluid dw-shell-view">

    <?php View::process($page_module, $page_title, $set_title); ?>

    <?php echo DwForm::open('', 'post', array('id'=>'form', 'class'=>'dw-validate')); ?>

        <div class="row-fluid">
            <div class="span6">
                        <?php echo DwForm::number('parroco.nuip', array('class'=>'input-xxlarge input-required mask-pint show-error'), NULL, 'Cédula'); ?>
                    </div>
            <div class="span6">
            </div>
        </div>
        <div class="row-fluid">
            <div class="span6">
                <?php echo DwForm::text('parroco.nombre', array('class'=>'input-xlarge input-required show-error data-toggle="tooltip" title="Ingrese el Nombre del Feligres"'), NULL, 'Nombre'); ?>
            </div>

            <div class="span6">
                        <?php echo DwForm::text('parroco.apellido', array('class'=>'input-xxlarge input-required mask-alphanum show-error'), NULL, 'Apellido'); ?>
                    </div>
        </div>

        <div class="row-fluid">
            <div class="span6">
                        <?php echo DwForm::date('parroco.fecha_nacimiento', array('class'=>'input-xlarge input-required mask-date input-date show-errors'), date("Y-m-d"), 'Fecha de Nacimiento'); ?>
                    </div>

             <div class="span6">
                        <?php echo DwForm::tel('parroco.telefono', array('class'=>'input-numeric mask-pint show-error'), NULL, 'Teléfono'); ?>
                    </div>
        </div>

        <div class="row-fluid">
            <div class="span6">
                <?php echo DwForm::textarea('parroco.direccion_habitacion', array('class'=>'input-xxlarge input-required show-error data-toggle="tooltip" title="Ingrese la Dirección del Feligres"'), NULL, 'Dirección'); ?>
            </div>
            <div class="span6">
                        <?php echo DwForm::dbSelect('parroco.tipo_nuip_id', 'tipo_nuip', array('params/tipo_nuip', 'getListadoTipoNuip'), NULL, array('class'=>'input-xxlarge input-required mask-pint show-errors'), NULL, 'Sexo'); ?>
                    </div>
            
        </div>


        <div class="row-fluid">
            <div class="form-actions">
                <?php echo DwButton::save('Guardar parroco'); ?>
                <?php echo DwButton::reset('form'); ?>
                <?php echo DwButton::cancel('config/parroco/listar/'); ?>
            </div>
        </div>

    <?php echo DwForm::close(); ?>

</div>
