<?php View::notify(); ?>
<script type="text/javascript">
    $(function() {
        $('table').dwGrid({
            form_search: true,
            form_action: '<?php echo PUBLIC_PATH; ?>config/parroco/buscar/',
            form_load_data : 'dw-shell-content',
            order_attr: '<?php echo (APP_AJAX) ? 'class="dw-ajax dw-spinner"' : ''; ?>',
            order_action: $.KumbiaPHP.publicPath+"config/parroco/buscar/<?php echo $field.'/'.$value.'/'; ?>"
        });
    });
</script>

<div class="container-fluid dw-shell-view">

    <?php View::process($page_module, $page_title, $set_title); ?>

    <div class="btn-toolbar btn-toolbar-top">
        <div class="btn-actions">
            <?php echo DwHtml::button("config/parroco/agregar/", 'agregar', array('class'=>'btn-success'), 'check', APP_AJAX); ?>
            <?php echo DwHtml::button("config/parroco/listar/", 'listar', array('class'=>'btn-warning'), 'ok', APP_AJAX); ?>
        </div>
    </div>

    <div class="dw-overflow" id="data-result">

        <table class="table table-bordered table-hover table-striped table-condensed table-responsive">
            <thead>
                <tr>
                    <th>NUM</th>
                    <th class="col-collapse" data-search="nuip">Cédula</th>
                    <th class="col-collapse" data-search="nombre">Nombre</th>
                    <th class="col-collapse">ESTADO</th>
                    <th class="btn-actions no-responsive" style="width: 100px;">ACCIONES</th>
                </tr>
            </thead>
            <tbody>
                <?php if($parrocos) { ?>
                <?php foreach($parrocos->items as $parroco): ?>
                    <?php $key_upd = DwSecurity::getKey($parroco->id, 'upd_feligres'); ?>
                     <?php $key_inac = DwSecurity::getKey($parroco->id, 'inactivar_feligres'); ?>
                    <?php $key_reac = DwSecurity::getKey($parroco->id, 'reactivar_feligres'); ?>
                   <tr>
                        <td><?php echo $parrocos->counter; ?></td>
                         <td><?php echo ($field=='nuip') ? DwUtils::resaltar($value, $parroco->nuip) : $parroco->nuip; ?></td>
                        <td><?php echo ($field=='nombre') ? DwUtils::resaltar($value, $parroco->nombre) : $parroco->nombre; ?></td>
                           <td><?php echo ($parroco->estado == Parroco::ACTIVO) ? '<span class="label label-success">Activo</span>' : '<span class="label label-important">Inactivo</span>'; ; ?></td>
                        <td>
                            <?php echo DwHtml::buttonTable('Modificar parroco', "config/parroco/editar/$key_upd/", NULL, 'info', 'edit'); ?>
                           <?php if($parroco->estado == Parroco::ACTIVO) { ?>
                                <?php echo DwHtml::buttonTable('Inactivar parroco', "config/parroco/estado/inactivar/$key_inac/", null, 'success', 'flag'); ?>
                            <?php } else { ?>
                                <?php echo DwHtml::buttonTable('Reactivar parroco', "config/parroco/estado/reactivar/$key_reac/", null, 'danger', 'flag'); ?>
                            <?php } ?>                 
                        </td>
                    </tr>
                    <?php $parrocos->counter++; ?>
                <?php endforeach; ?>
            </tbody>
            <?php } ?>
        </table>

    </div>

    <?php View::partial('paginators/default', false, array('page'=>$parrocos, 'url'=>"config/parroco/buscar/$field/$value/$order/")); ?>
</div>
