<?php View::notify(); ?>

<script type="text/javascript">
    $(function() {
        $('table').dwGrid({
             form_search: true,
            form_action: '<?php echo PUBLIC_PATH; ?>config/parroco/buscar/',
            form_load_data : 'dw-shell-content',
            order_attr: '<?php echo (APP_AJAX) ? 'class="dw-ajax dw-spinner"' : ''; ?>',
            order_action: $.KumbiaPHP.publicPath+"config/feligres/listar/"
        });
    });
</script>

<div class="container-fluid dw-shell-view">

    <?php View::process($page_module, $page_title, $set_title); ?>

    <div class="btn-toolbar btn-toolbar-top">
        <div class="btn-actions">
            <?php echo DwHtml::button("config/parroco/agregar/", 'agregar', array('class'=>'btn-success'), 'check', APP_AJAX); ?>
        </div>
    </div>

    <div class="dw-overflow">

        <table class="table table-bordered table-hover table-striped table-condensed table-responsive">
            <thead>
                <tr>
                    <th>NUM</th>
                    <th class="col-collapse" data-search="nuip">CEDULA</th>
                    <th class="col-collapse" data-search="nombre">NOMBRE</th>
                    <th class="col-collapse" data-search="apellido">APELLIDO</th>
                    <th class="col-collapse" data-search="telefono">TELÉFONO</th>
                    <th class="col-collapse" data-search="direccion_habitacion">DIRECCIÓN</th>
                     <th class="col-collapse">ESTADO</th>
                    <th class="btn-actions no-responsive">ACCIONES</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach($parrocos->items as $parroco): ?>
                    <?php $key_upd = DwSecurity::getKey($parroco->id, 'upd_parroco'); ?>
                     <?php $key_inac = DwSecurity::getKey($parroco->id, 'inactivar_parroco'); ?>
                    <?php $key_reac = DwSecurity::getKey($parroco->id, 'reactivar_parroco'); ?>
                    <tr>
                        <td><?php echo $parrocos->counter; ?></td>
                        <td><?php echo empty($parroco->nuip) ? '' : $parroco->nuip; ?></td>
                         <td><?php echo empty($parroco->nombre) ? '' : $parroco->nombre; ?></td> 
                        <td><?php echo $parroco->apellido; ?></td>
                        <td><?php echo $parroco->telefono; ?></td>
                        <td><?php echo $parroco->direccion_habitacion; ?></td>
                        <td><?php echo ($parroco->estado == Parroco::ACTIVO) ? '<span class="label label-success">Activo</span>' : '<span class="label label-important">Inactivo</span>'; ; ?></td>
                        <td>
                            <?php echo DwHtml::buttonTable('Modificar parroco', "config/parroco/editar/$key_upd/", null, 'info', 'edit'); ?>
                           <?php if($parroco->estado == Parroco::ACTIVO) { ?>
                                <?php echo DwHtml::buttonTable('Inactivar parroco', "config/parroco/estado/inactivar/$key_inac/", null, 'success', 'flag'); ?>
                            <?php } else { ?>
                                <?php echo DwHtml::buttonTable('Reactivar parroco', "config/parroco/estado/reactivar/$key_reac/", null, 'danger', 'flag'); ?>
                            <?php } ?>
                        </td>
                    </tr>
                    <?php $parrocos->counter++; ?>
                <?php endforeach; ?>
            </tbody>
        </table>

    </div>

    <?php View::partial('paginators/default', false, array('page'=>$parrocos, 'url'=>"config/parrocos/listar/$order/")); ?>

</div>