<?php View::notify(); ?>

<script type="text/javascript">
    $(function() {
        $('table').dwGrid({
             form_search: true,
            form_action: '<?php echo PUBLIC_PATH; ?>inventario/entrada/buscar/',
            form_load_data : 'dw-shell-content',
            order_attr: '<?php echo (APP_AJAX) ? 'class="dw-ajax dw-spinner"' : ''; ?>',
            order_action: $.KumbiaPHP.publicPath+"inventario/entrada/listar/"
        });
    });
</script>

<div class="container-fluid dw-shell-view">

    <?php View::process($page_module, $page_title, $set_title); ?>

    <div class="btn-toolbar btn-toolbar-top">
        <div class="btn-actions">
            <?php echo DwHtml::button("inventario/entrada/agregar/", 'agregar', array('class'=>'btn-success'), 'check', APP_AJAX); ?>
        </div>
    </div>

    <div class="dw-overflow">

        <table class="table table-bordered table-hover table-striped table-condensed table-responsive">
            <thead>
                <tr>
                    <th>NUM</th>
                    <th class="col-collapse" data-search="id">Numero</th>
                    <th class="col-collapse" data-search="nombre">Chofer</th>
                    <th class="col-collapse">Producto</th>
                    <th class="col-collapse">Cantidad</th>

                </tr>
            </thead>
            <tbody>
                <?php foreach($entradas->items as $entrada): ?>
                    <?php $key_upd = DwSecurity::getKey($entrada->id, 'upd_entrada'); ?>
                     <?php $key_inac = DwSecurity::getKey($entrada->id, 'inactivar_entrada'); ?>
                    <?php $key_reac = DwSecurity::getKey($entrada->id, 'reactivar_entrada'); ?>
                    <tr>
                        <td><?php echo $entradas->counter; ?></td>
                        <td><?php echo empty($entrada->numerocontrol) ? '' : $entrada->numerocontrol; ?></td>
                         <td><?php echo empty($entrada->nombrechofer) ? '' : $entrada->nombrechofer; ?></td> 
                        <td><?php echo $entrada->producto; ?></td>
                        <td><?php echo $entrada->cantidadproducto; ?></td>
                        <td>
                            <?php echo DwHtml::buttonTable('Modificar entrada', "inventario/entrada/editar/$key_upd/", null, 'info', 'edit'); ?>
                           <?php if($entrada->estado == Entrada::ACTIVO) { ?>
                                <?php echo DwHtml::buttonTable('Inactivar entrada', "inventario/entrada/estado/inactivar/$key_inac/", null, 'success', 'flag'); ?>
                            <?php } else { ?>
                                <?php echo DwHtml::buttonTable('Reactivar entrada', "inventario/entrada/estado/reactivar/$key_reac/", null, 'danger', 'flag'); ?>
                            <?php } ?>
                        </td>
                    </tr>
                    <?php $entradas->counter++; ?>
                <?php endforeach; ?>
            </tbody>
        </table>

    </div>

    <?php View::partial('paginators/default', false, array('page'=>$entradas, 'url'=>"inventario/entrada/listar/$order/")); ?>

</div>