<?php View::notify(); ?>

<div class="container-fluid dw-shell-view">

    <?php View::process($page_module, $page_title, $set_title); ?>

    <?php echo DwForm::open('', 'post', array('id'=>'form', 'class'=>'dw-validate')); ?>

       <div class="row-fluid">
            
            <div class="span6">
                <?php echo DwForm::text('proyecto.nombreproyecto', array('class'=>'input-xlarge input-required show-error data-toggle="tooltip" title="Ingrese el Nombre del Proyecto"'), NULL, 'Nombre Proyecto'); ?>
            </div>
        </div>
        <div class="row-fluid">
            <div class="span6">
                <?php echo DwForm::number('proyecto.cantfamiliar', array('class'=>'input-numeric input-required show-error data-toggle="tooltip" title=""'), NULL, 'Cantidad de casas Familiar'); ?>
            </div>

            <div class="span6">
                <?php echo DwForm::number('proyecto.cantbifamiliar', array('class'=>'input-numeric input-required input-xlarge mask-pint show-error data-toggle="tooltip" title=""'), NULL, 'Cantidad de casas Bifamiliar'); ?>
            </div>
        </div>

        <div class="row-fluid">
            <div class="span6">
                 <?php echo DwForm::number('proyecto.canttetra', array('class'=>'input-numeric input-required input-xlarge mask-pint show-error data-toggle="tooltip" title=""'), NULL, 'Cantidad de casas Tetra'); ?>
                
            </div>
        <div class="span6">
                <?php echo DwForm::number('proyecto.canttotal', array('class'=>'input-numeric input-required input-xlarge mask-pint show-error data-toggle="tooltip" title=""'), NULL, 'Cantidad total de casas'); ?>
        </div>
            
         <div class="row-fluid">
            <div class="span6">
                <?php echo DwForm::date('proyecto.fechai', array('class'=>'input-xlarge input-required mask-date input-date show-errors'), date("Y-m-d"), 'Fecha de inicio'); ?>
            </div>     
            <div class="span6">
                <?php echo DwForm::dbSelect('', array('nombreEstado'), array('config/estado', 'getListadoSelect'), array('todas'=>'Seleccione'), array('class'=>'input-xlarge  mask-pint show-errors data-toggle="tooltip" title="Selecciona un estado"'), NULL, 'Estado'); ?>
             </div>
        </div>
            <div class="row-fluid">
                <div class="span6">
                <?php echo DwForm::dbSelect('', array('nombremunicipio'), array('config/municipio', 'getListadoSelect'), array('todas'=>'Seleccione'), array('class'=>'input-xlarge  mask-pint show-errors data-toggle="tooltip" title="Selecciona un municipio"'), NULL, 'Municipio'); ?>
                </div>
                 <div class="span6">
                 <?php echo DwForm::dbSelect('proyecto.idciudad', array('nombreciudad'), array('config/ciudad', 'getListadoSelect'), array('todas'=>'Seleccione'), array('class'=>'input-xlarge input-required mask-pint show-errors data-toggle="tooltip" title="Selecciona una ciudad"'), NULL, 'Ciudad'); ?>
                </div>
            </div>

        <div class="row-fluid">
            <div class="span6">
                
                <?php echo DwForm::dbSelect('proyecto.responsableuno', array('nombre'), array('proyecto/responsable', 'getListadoSelect'), array('todas'=>'Seleccione'), array('class'=>'input-xlarge input-required mask-pint show-errors data-toggle="tooltip" title="Selecciona una persona"'), NULL, 'Ingeniero Responsable'); ?>
            </div>
            <div class="span6">
                
                <?php echo DwForm::dbSelect('proyecto.responsabledos', array('nombre'), array('proyecto/responsable', 'getListadoSelect'), array('todas'=>'Seleccione'), array('class'=>'input-xlarge input-required mask-pint show-errors data-toggle="tooltip" title="Selecciona una persona"'), NULL, 'Ingeniero Inspector'); ?>
            </div>
        </div>
        <div class="row-fluid">
            <div class="span6">
                
                <?php echo DwForm::dbSelect('proyecto.responsabletres', array('nombre'), array('proyecto/responsable', 'getListadoSelect'), array('todas'=>'Seleccione'), array('class'=>'input-xlarge input-required mask-pint show-errors data-toggle="tooltip" title="Selecciona una persona"'), NULL, 'Vocero de la comunidad'); ?>
            </div>
        </div>    
           
            
        </div>

            <?php echo DwForm::hiddenKey('proyecto.idproyecto', $proyecto->idproyecto); ?>

        <div class="row-fluid">
            <div class="form-actions">
                <?php echo DwButton::save('Guardar Nombre'); ?>
                <?php echo DwButton::reset('form'); ?>
                <?php echo DwButton::cancel('proyecto/proyecto/listar/'); ?>
            </div>
        </div>

    <?php echo DwForm::close(); ?>

</div>