<?php View::notify(); ?>

<script type="text/javascript">
    $(function() {
        $('table').dwGrid({
             form_search: true,
            form_action: '<?php echo PUBLIC_PATH; ?>inventario/producto/buscar/',
            form_load_data : 'dw-shell-content',
            order_attr: '<?php echo (APP_AJAX) ? 'class="dw-ajax dw-spinner"' : ''; ?>',
            order_action: $.KumbiaPHP.publicPath+"inventario/producto/listar/"
        });
    });
</script>

<div class="container-fluid dw-shell-view">

    <?php View::process($page_module, $page_title, $set_title); ?>

    <div class="btn-toolbar btn-toolbar-top">
        <div class="btn-actions">
            <?php echo DwHtml::button("inventario/producto/agregar/", 'agregar', array('class'=>'btn-success'), 'check', APP_AJAX); ?>
        </div>
    </div>

    <div class="dw-overflow">

        <table class="table table-bordered table-hover table-striped table-condensed table-responsive">
            <thead>
                <tr>
                    <th>NUM</th>
                    <th class="col-collapse" data-search="idproducto">CODIGO</th>
                    <th class="col-collapse" data-search="nombreproducto">NOMBRE</th>
                    <th class="col-collapse">GRUPO</th>
                    <th class="col-collapse">SUBGRUPO</th>
                    
                </tr>
            </thead>
            <tbody>
                <?php foreach($productos->items as $Producto): ?>
                    
                    <tr>
                        <td><?php echo $productos->counter; ?></td>
                        <td><?php echo empty($Producto->idproducto) ? '' : $Producto->idproducto; ?></td>
                         <td><?php echo empty($Producto->nombreproducto) ? '' : $Producto->nombreproducto; ?></td> 
                        <td><?php echo $Producto->grupoo; ?></td>
                        <td><?php echo $Producto->subgrupoo; ?></td>
                        
                        
                    </tr>
                    <?php $productos->counter++; ?>
                <?php endforeach; ?>
            </tbody>
        </table>

    </div>

    <?php View::partial('paginators/default', false, array('page'=>$productos, 'url'=>"inventario/producto/listar/$order/")); ?>

</div>