<?php View::notify(); ?>
<script type="text/javascript">
    $(function() {
        $('table').dwGrid({
            form_search: true,
            form_action: '<?php echo PUBLIC_PATH; ?>proyecto/proyecto/buscar/',
            form_load_data : 'dw-shell-content',
            order_attr: '<?php echo (APP_AJAX) ? 'class="dw-ajax dw-spinner"' : ''; ?>',
            order_action: $.KumbiaPHP.publicPath+"proyecto/proyecto/buscar/<?php echo $field.'/'.$value.'/'; ?>"
        });
    });
</script>

<div class="container-fluid dw-shell-view">

    <?php View::process($page_module, $page_title, $set_title); ?>

    <div class="btn-toolbar btn-toolbar-top">
        <div class="btn-actions">
            <?php echo DwHtml::button("proyecto/proyecto/agregar/", 'agregar', array('class'=>'btn-success'), 'check', APP_AJAX); ?>
            <?php echo DwHtml::button("proyecto/proyecto/listar/", 'listar', array('class'=>'btn-warning'), 'ok', APP_AJAX); ?>
        </div>
    </div>

    <div class="dw-overflow" id="data-result">

        <table class="table table-bordered table-hover table-striped table-condensed table-responsive">
            <thead>
                <tr>
                    <th>NUM</th>
                    <th class="col-collapse" data-search="idproyecto">CODIGO</th>
                    <th class="col-collapse" data-search="nombreproyecto">NOMBRE</th>
                    <th class="col-collapse">ESTADO</th>
                    <th class="btn-actions no-responsive" style="width: 100px;">ACCIONES</th>
                </tr>
            </thead>
            <tbody>
                <?php if($proyecto) { ?>
                <?php foreach($proyecto->items as $proyecto): ?>
                    <?php $key_upd = DwSecurity::getKey($proyecto->id, 'upd_proyecto'); ?>
                     <?php $key_inac = DwSecurity::getKey($proyecto->id, 'inactivar_proyecto'); ?>
                    <?php $key_reac = DwSecurity::getKey($proyecto->id, 'reactivar_proyecto'); ?>
                   <tr>
                        <td><?php echo $proyecto->counter; ?></td>
                         <td><?php echo ($field=='idproyecto') ? DwUtils::resaltar($value, $proyecto->idproyecto) : $proyecto->idproyecto; ?></td>
                        <td><?php echo ($field=='nombreproyecto') ? DwUtils::resaltar($value, $proyecto->nombreproyecto) : $proyecto->nombreproyecto; ?></td>
                           <td><?php echo ($proyecto->estado == Proyecto::ACTIVO) ? '<span class="label label-success">Activo</span>' : '<span class="label label-important">Inactivo</span>'; ; ?></td>
                        <td>
                            <?php echo DwHtml::buttonTable('Modificar proyecto', "proyecto/proyecto/editar/$key_upd/", NULL, 'info', 'edit'); ?>
                           <?php if($proyecto->estado == Proyecto::ACTIVO) { ?>
                                <?php echo DwHtml::buttonTable('Inactivar proyecto', "proyecto/proyecto/estado/inactivar/$key_inac/", null, 'success', 'flag'); ?>
                            <?php } else { ?>
                                <?php echo DwHtml::buttonTable('Reactivar proyecto', "proyecto/proyecto/estado/reactivar/$key_reac/", null, 'danger', 'flag'); ?>
                            <?php } ?>                 
                        </td>
                    </tr>
                    <?php $proyecto->counter++; ?>
                <?php endforeach; ?>
            </tbody>
            <?php } ?>
        </table>

    </div>

    <?php View::partial('paginators/default', false, array('page'=>$proyecto, 'url'=>"proyecto/proyecto/buscar/$field/$value/$order/")); ?>
</div>
