<?php View::notify(); ?>
<script type="text/javascript">
    $(function() {
        $('table').dwGrid({
            form_search: true,
            form_action: '<?php echo PUBLIC_PATH; ?>proyecto/avance/buscar/',
            form_load_data : 'dw-shell-content',
            order_attr: '<?php echo (APP_AJAX) ? 'class="dw-ajax dw-spinner"' : ''; ?>',
            order_action: $.KumbiaPHP.publicPath+"proyecto/avance/buscar/<?php echo $field.'/'.$value.'/'; ?>"
        });
    });
</script>

<div class="container-fluid dw-shell-view">

    <?php View::process($page_module, $page_title, $set_title); ?>

    <div class="btn-toolbar btn-toolbar-top">
        <div class="btn-actions">
            <?php echo DwHtml::button("proyecto/avance/agregar/", 'agregar', array('class'=>'btn-success'), 'check', APP_AJAX); ?>
            <?php echo DwHtml::button("proyecto/avance/listar/", 'listar', array('class'=>'btn-warning'), 'ok', APP_AJAX); ?>
        </div>
    </div>

    <div class="dw-overflow" id="data-result">

        <table class="table table-bordered table-hover table-striped table-condensed table-responsive">
            <thead>
                <tr>
                    <th>NUM</th>
                    <th class="col-collapse" data-search="idproyecto">PROYECTO</th>
                    <th class="col-collapse" data-search="nombre">NOMBRE</th>
                    <th class="col-collapse">ESTADO</th>
                    <th class="btn-actions no-responsive" style="width: 100px;">ACCIONES</th>
                </tr>
            </thead>
            <tbody>
                <?php if($avances) { ?>
                <?php foreach($avances->items as $avance): ?>
                    <?php $key_upd = DwSecurity::getKey($avance->id, 'upd_parroco'); ?>
                     <?php $key_inac = DwSecurity::getKey($avance->id, 'inactivar_avance'); ?>
                    <?php $key_reac = DwSecurity::getKey($avance->id, 'reactivar_avance'); ?>
                   <tr>
                        <td><?php echo $avances->counter; ?></td>
                         <td><?php echo ($field=='idproyecto') ? DwUtils::resaltar($value, $avance->idproyecto) : $avance->idproyecto; ?></td>
                        <td><?php echo ($field=='nombre') ? DwUtils::resaltar($value, $avance->nombre) : $avance->nombre; ?></td>
                           <td><?php echo ($avance->estado == Avance::ACTIVO) ? '<span class="label label-success">Activo</span>' : '<span class="label label-important">Inactivo</span>'; ; ?></td>
                        <td>
                            <?php echo DwHtml::buttonTable('Modificar avance', "proyecto/avance/editar/$key_upd/", NULL, 'info', 'edit'); ?>
                           <?php if($avance->estado == Avance::ACTIVO) { ?>
                                <?php echo DwHtml::buttonTable('Inactivar avance', "proyecto/avance/estado/inactivar/$key_inac/", null, 'success', 'flag'); ?>
                            <?php } else { ?>
                                <?php echo DwHtml::buttonTable('Reactivar avance', "proyecto/avance/estado/reactivar/$key_reac/", null, 'danger', 'flag'); ?>
                            <?php } ?>                 
                        </td>
                    </tr>
                    <?php $avancees->counter++; ?>
                <?php endforeach; ?>
            </tbody>
            <?php } ?>
        </table>

    </div>

    <?php View::partial('paginators/default', false, array('page'=>$avances, 'url'=>"proyecto/avance/buscar/$field/$value/$order/")); ?>
</div>
