<?php View::notify(); ?>

<div class="container-fluid dw-shell-view">

    <?php View::process($page_module, $page_title, $set_title); ?>

    <?php echo DwForm::open('', 'post', array('id'=>'form', 'class'=>'dw-validate')); ?>

        <div class="row-fluid">
            <div class="span6">
                <?php echo DwForm::text('avance.idproyecto', array('class'=>'input-required mask-alphanum show-error'), $avance->idproyecto, 'idproyecto'); ?>
            </div>
            <div class="span6">
            </div>
        </div>
        <div class="row-fluid">
            <div class="span6">
                <?php echo DwForm::text('avance.nombre', array('class'=>'input-required mask-text show-error input-xxlarge'), $avance->nombre, 'Nombre'); ?>
            </div>

            <div class="span6">
                <?php echo DwForm::text('avance.apellido', array('class'=>'input-required mask-text show-error input-xxlarge'), $avance->apellido, 'Apellido'); ?>
            </div>
        </div>

        <div class="row-fluid">
            <div class="span6">
                <?php echo DwForm::text('avance.telefono', array('class'=>'input-xxlarge input-required mask-alphanum show-error'), $avance->telefono, 'Teléfono'); ?>
            </div>

           <div class="span6">
                        <?php echo DwForm::date('avance.fecha_nacimiento', array('class'=>'input-xlarge input-required mask-date input-date show-errors'), date("Y-m-d"), $avance->fecha_nacimiento, 'Fecha de Nacimiento'); ?>
                    </div>
        </div>

        <div class="row-fluid">

            <div class="span6">
                <?php echo DwForm::textarea('avance.direccion_habitacion', array('class'=>'input-xxlarge input-required show-error'), $avance->direccion_habitacion, 'Dirección'); ?>
            </div>
          
        </div>      

            <?php echo DwForm::hiddenKey('avance.id', $avance->id); ?>

        <div class="row-fluid">
            <div class="form-actions">
                <?php echo DwButton::save('Guardar Nombre'); ?>
                <?php echo DwButton::reset('form'); ?>
                <?php echo DwButton::cancel('proyecto/avance/listar/'); ?>
            </div>
        </div>

    <?php echo DwForm::close(); ?>

</div>