<?php View::notify(); ?>

<div class="container-fluid dw-shell-view">

    <?php View::process($page_module, $page_title, $set_title); ?>

    <?php echo DwForm::open('', 'post', array('id'=>'form', 'class'=>'dw-validate')); ?>

        <div class="row-fluid">
            <div class="span6">
                <?php echo DwForm::text('proveedor.rif', array('class'=>'input-xlarge input-required show-error data-toggle="tooltip" title="Ingrese RIF del Proveedor"'), NULL, 'Rif'); ?>
            </div>
            <div class="span6">
            </div>
        </div>
        <div class="row-fluid">
            <div class="span6">
                <?php echo DwForm::text('proveedor.nombre', array('class'=>'input-xlarge input-required show-error data-toggle="tooltip" title="Ingrese el Nombre del Proveedor"'), NULL, 'Nombre'); ?>
            </div>

            <div class="span6">
                <?php echo DwForm::text('proveedor.razon', array('class'=>'input-xlarge input-required show-error data-toggle="tooltip" title="Ingrese Razón Social del Proveedor"'), NULL, 'Razón Social'); ?>
            </div>
        </div>

        <div class="row-fluid">
            <div class="span6">
                <?php echo DwForm::text('proveedor.telefono', array('class'=>'input-numeric input-required input-xlarge mask-pint show-error data-toggle="tooltip" title="Ingrese Teléfono Fijo del Proveedor"'), NULL, 'Teléfono'); ?>
            </div>

            <div class="span6">
                <?php echo DwForm::email('proveedor.email', array('class'=>'input-xlarge show-error data-toggle="tooltip" title="Ingrese Correo Electrónico del Proveedor"'), NULL, 'Correo Electrónico'); ?>
            </div>
        </div>

        <div class="row-fluid">
            <div class="span6">
                <?php echo DwForm::textarea('proveedor.direccion', array('class'=>'input-xxlarge input-required show-error data-toggle="tooltip" title="Ingrese la Dirección del Proveedor"'), NULL, 'Dirección'); ?>
            </div>
            <div class="span6">
                <?php echo DwForm::textarea('proveedor.observacion', array('class'=>'input-xxlarge show-error data-toggle="tooltip" title="Ingrese Observación acerca del proveedor"'), NULL, 'Observación'); ?>
            </div>
            
        </div>


        <div class="row-fluid">
            <div class="form-actions">
                <?php echo DwButton::save('Guardar proveedor'); ?>
                <?php echo DwButton::reset('form'); ?>
                <?php echo DwButton::cancel('inventario/proveedor/listar/'); ?>
            </div>
        </div>

    <?php echo DwForm::close(); ?>

</div>
