<?php View::notify(); ?>

<div class="container-fluid dw-shell-view">

    <?php View::process($page_module, $page_title, $set_title); ?>

    <?php echo DwForm::open('', 'post', array('id'=>'form', 'class'=>'dw-validate')); ?>

        <div class="row-fluid">
            <div class="span6">
                <?php echo DwForm::text('proveedor.rif', array('class'=>'input-required mask-alphanum show-error'), $proveedor->rif, 'Rif'); ?>
            </div>
            <div class="span6">
            </div>
        </div>
        <div class="row-fluid">
            <div class="span6">
                <?php echo DwForm::text('proveedor.nombre', array('class'=>'input-required mask-text show-error input-xxlarge'), $proveedor->nombre, 'Nombre'); ?>
            </div>

            <div class="span6">
                <?php echo DwForm::text('proveedor.razon', array('class'=>'input-required mask-text show-error input-xxlarge'), $proveedor->razon, 'Razon Social'); ?>
            </div>
        </div>

        <div class="row-fluid">
            <div class="span6">
                <?php echo DwForm::text('proveedor.telefono', array('class'=>'input-xxlarge input-required mask-alphanum show-error'), $proveedor->telefono, 'Teléfono'); ?>
            </div>

            <div class="span6">
                <?php echo DwForm::email('proveedor.email', array('class'=>'input-xxlarge show-error'), $proveedor->email, 'Correo Electronico'); ?>
            </div>
        </div>

        <div class="row-fluid">

            <div class="span6">
                <?php echo DwForm::textarea('proveedor.direccion', array('class'=>'input-xxlarge input-required show-error'), $proveedor->direccion, 'Dirección'); ?>
            </div>
            <div class="span6">
                <?php echo DwForm::textarea('proveedor.observacion', array('class'=>'input-xxlarge show-error'), $proveedor->observacion, 'Observación'); ?>
            </div>
        </div>      

            <?php echo DwForm::hiddenKey('proveedor.id', $proveedor->id); ?>

        <div class="row-fluid">
            <div class="form-actions">
                <?php echo DwButton::save('Guardar proveedor'); ?>
                <?php echo DwButton::reset('form'); ?>
                <?php echo DwButton::cancel('inventario/proveedor/listar/'); ?>
            </div>
        </div>

    <?php echo DwForm::close(); ?>

</div>