<?php View::notify(); ?>
<script type="text/javascript">
    $(function() {
        $('table').dwGrid({
            form_search: true,
            form_action: '<?php echo PUBLIC_PATH; ?>proyecto/responsable/buscar/',
            form_load_data : 'dw-shell-content',
            order_attr: '<?php echo (APP_AJAX) ? 'class="dw-ajax dw-spinner"' : ''; ?>',
            order_action: $.KumbiaPHP.publicPath+"proyecto/responsable/buscar/<?php echo $field.'/'.$value.'/'; ?>"
        });
    });
</script>

<div class="container-fluid dw-shell-view">

    <?php View::process($page_module, $page_title, $set_title); ?>

    <div class="btn-toolbar btn-toolbar-top">
        <div class="btn-actions">
            <?php echo DwHtml::button("proyecto/responsable/agregar/", 'agregar', array('class'=>'btn-success'), 'check', APP_AJAX); ?>
            <?php echo DwHtml::button("proyecto/responsable/listar/", 'listar', array('class'=>'btn-warning'), 'ok', APP_AJAX); ?>
        </div>
    </div>

    <div class="dw-overflow" id="data-result">

        <table class="table table-bordered table-hover table-striped table-condensed table-responsive">
            <thead>
                <tr>
                    <th>NUM</th>
                    <th class="col-collapse" data-search="cedula">CEDULA</th>
                    <th class="col-collapse" data-search="nombre">NOMBRE</th>
                    <th class="col-collapse">ESTADO</th>
                    <th class="btn-actions no-responsive" style="width: 100px;">ACCIONES</th>
                </tr>
            </thead>
            <tbody>
                <?php if($responsables) { ?>
                <?php foreach($responsables->items as $responsable): ?>
                    <?php $key_upd = DwSecurity::getKey($responsable->id, 'upd_parroco'); ?>
                     <?php $key_inac = DwSecurity::getKey($responsable->id, 'inactivar_responsable'); ?>
                    <?php $key_reac = DwSecurity::getKey($responsable->id, 'reactivar_responsable'); ?>
                   <tr>
                        <td><?php echo $responsables->counter; ?></td>
                         <td><?php echo ($field=='cedula') ? DwUtils::resaltar($value, $responsable->cedula) : $responsable->cedula; ?></td>
                        <td><?php echo ($field=='nombre') ? DwUtils::resaltar($value, $responsable->nombre) : $responsable->nombre; ?></td>
                           <td><?php echo ($responsable->estado == Responsable::ACTIVO) ? '<span class="label label-success">Activo</span>' : '<span class="label label-important">Inactivo</span>'; ; ?></td>
                        <td>
                            <?php echo DwHtml::buttonTable('Modificar responsable', "proyecto/responsable/editar/$key_upd/", NULL, 'info', 'edit'); ?>
                           <?php if($responsable->estado == Responsable::ACTIVO) { ?>
                                <?php echo DwHtml::buttonTable('Inactivar responsable', "proyecto/responsable/estado/inactivar/$key_inac/", null, 'success', 'flag'); ?>
                            <?php } else { ?>
                                <?php echo DwHtml::buttonTable('Reactivar responsable', "proyecto/responsable/estado/reactivar/$key_reac/", null, 'danger', 'flag'); ?>
                            <?php } ?>                 
                        </td>
                    </tr>
                    <?php $responsables->counter++; ?>
                <?php endforeach; ?>
            </tbody>
            <?php } ?>
        </table>

    </div>

    <?php View::partial('paginators/default', false, array('page'=>$responsables, 'url'=>"proyecto/responsable/buscar/$field/$value/$order/")); ?>
</div>
