<?php View::notify(); ?>

<div class="container-fluid dw-shell-view">

    <?php View::process($page_module, $page_title, $set_title); ?>

    <?php echo DwForm::open('', 'post', array('id'=>'form', 'class'=>'dw-validate')); ?>

        <div class="row-fluid">
            <div class="span6">
                <?php echo DwForm::text('responsable.cedula', array('class'=>'input-required mask-alphanum show-error'), $responsable->cedula, 'Cedula'); ?>
            </div>
            <div class="span6">
            </div>
        </div>
        <div class="row-fluid">
            <div class="span6">
                <?php echo DwForm::text('responsable.nombre', array('class'=>'input-required mask-text show-error input-xxlarge'), $responsable->nombre, 'Nombre'); ?>
            </div>

            <div class="span6">
                <?php echo DwForm::text('responsable.apellido', array('class'=>'input-required mask-text show-error input-xxlarge'), $responsable->apellido, 'Apellido'); ?>
            </div>
        </div>

        <div class="row-fluid">
            <div class="span6">
                <?php echo DwForm::text('responsable.telefono', array('class'=>'input-xxlarge input-required mask-alphanum show-error'), $responsable->telefono, 'Teléfono'); ?>
            </div>

           <div class="span6">
                        <?php echo DwForm::date('responsable.fecha_nacimiento', array('class'=>'input-xlarge input-required mask-date input-date show-errors'), date("Y-m-d"), $responsable->fecha_nacimiento, 'Fecha de Nacimiento'); ?>
                    </div>
        </div>

        <div class="row-fluid">

            <div class="span6">
                <?php echo DwForm::textarea('responsable.direccion_habitacion', array('class'=>'input-xxlarge input-required show-error'), $responsable->direccion_habitacion, 'Dirección'); ?>
            </div>
          
        </div>      

            <?php echo DwForm::hiddenKey('responsable.id', $responsable->id); ?>

        <div class="row-fluid">
            <div class="form-actions">
                <?php echo DwButton::save('Guardar Nombre'); ?>
                <?php echo DwButton::reset('form'); ?>
                <?php echo DwButton::cancel('proyecto/responsable/listar/'); ?>
            </div>
        </div>

    <?php echo DwForm::close(); ?>

</div>