<?php View::notify(); ?>

<div class="container-fluid dw-shell-view">

    <?php View::process($page_module, $page_title, $set_title); ?>

    <?php echo DwForm::open('', 'post', array('id'=>'form', 'class'=>'dw-validate')); ?>

        <div class="row-fluid">
            <div class="span4">
                <?php echo DwForm::text('grupo.nombre', array('class'=>'input-required mask-text show-error'), NULL, 'Nombre'); ?>
            </div>
            <div class="span4">
            </div>
        </div>
        <div class="row-fluid">
            <div class="span12">
                <?php echo DwForm::textarea('grupo.descripcion', array('class'=>'input-required mask-text show-error input-xxlarge'), NULL, 'Descripción'); ?>
            </div>
        </div>

        

        <div class="row-fluid">
            <div class="form-actions">
                <?php echo DwButton::save('Guardar grupo'); ?>
                <?php echo DwButton::reset('form'); ?>
                <?php echo DwButton::cancel('config/grupo/listar/'); ?>
            </div>
        </div>

    <?php echo DwForm::close(); ?>

</div>
